global:
  LogLevel: debug
  DebugServices: ssv/protocol/.*
  networks:
    - blox-docker

db:
  Path: ./data/db

eth2:
  ### replace with your beacon node address
  BeaconNodeAddr: 146.193.41.55:8000
  Network: prater
  MinGenesisTime: 1696582246


eth1:
  ### replace with your eth1 node WebSocket address
  ETH1Addr: ws://146.193.41.55:3334/ws

p2p:
  Discovery: mdns
  networks:
    - blox-docker
### replace with your ip and ports
### otherwise, the default ports (TCP 13001, UDP 12001) are used
  # HostAddress: 146.193.41.55
  TcpPort: 5004
  UdpPort: 4004
### mdns for local network setup
  # Bootnodes: enr:-LK4QMmL9hLJ1csDN4rQoSjlJGE2SvsXOETfcLH8uAVrxlHaELF0u3NeKCTY2eO_X1zy5eEKcHruyaAsGNiyyG4QWUQBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhCLdu_SJc2VjcDI1NmsxoQO8KQz5L1UEXzEr-CXFFq1th0eG6gopbdul2OQVMuxfMoN0Y3CCE4iDdWRwgg-g

ssv:
  GenesisEpoch: 1
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s
  networks:
    - blox-docker
  restart: always

### replace with your operator key
### NOTES:
###  - required for operators
###  - optional for exporters
OperatorPrivateKey:

LocalEventsPath: ./config/events.yaml