- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 1
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdTVTeXhYR0VNc1RYd0NJeUw3WE0KOW5rcTcyU3orZTBJQVZPRmtvckNnQjhXVTg5ellMa3dDZEw0SktRM3JQRlhLZ3BScTJCOWlJYnpXUXUzVkNGagpjUmRxRGYrMUt5ZjY2bHFIKzR3b2Y1dXMwZFpvU1FRRTRxZ2swTHY3WUZkQTdDV0hqbWtkQzNJV3haTkI3dCtBCm1hVEVDbGswcklZY244S0VaN0RMelMwb3ZCNytoK1lKYWV4Z2t2OStjdmE4WWZMeUhyZzNqZytGUDhhWlVsMTcKT21uUVJqL0dHK1pSVkdMcE1mbHdLOFprS3MrNXJONzBUSXB5L3JhRmlRSzF3RmVwTkRReFhVS21QVStBMDZSdQordktpL3hkUEtCb3ljN1N6aTBEQWxCdFhqa2FGdkxQSVJGa2J4a0k1SUtoNnpQbVVYWDlXNEM3SUNJRFB2L1dPCkd3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-1
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 2
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNWFLQzRob1pzaVVPbDAyNGNqNUMKZWdHUUhMRERqelZ3eTFEWHFvcTRlL0daWmdDQ3dpek81TVcwTjZUejJjNUtDNlZDNnF3d3hsWHJwaUh1bG9HcgpPSWZEODlTTks1RGh4bWpzcUpieHZUVHlaOFNGUUthb2lNRXd6WXVvUldacU04VnM3S2RvMUhMQU1RN2p4dXFwCmp0SUxIaU9EeHBUeU9nUmhPSnJhKzRUQzd6aTBWOUR4MnN0U1RVZlV2M1c3c0UwNWgwcUNzYVhmMERwd3hqVjgKbUJ6L2UwWjZiNFpEa3JIYkJRSk1ZTnJzcncrM210RjJxV3NhS1JzNWk1Ui9lMUZCMVJBaHNYMENBTHZpSTEyagpSMUNiaWVIQnh3RVZ2V1EzYm1qQVdXSW40SENVdmdacC9Ncm5OekxldUxaVUhKa1EzUXB5Q0IxQXlaSHRES1hzCmx3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-2
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 3
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBejdyOGJUWXNtQXRwbGp6a25YMTEKci9EdDBhc2E5ZXFnOC9PeGZmcExHTGZBYkduNFV6SStuUlF0dER0alIvZWhQWC9KVndiSEFpTnQ1MHJucXMweApxeDE5cGJ2bXhyakNQS0NaTXR2RzBFeGZORlFtWHdaZGZmQzg5WElwOHBHZG9yanRqWFlmWVF3ZS9WZGRRMC9HCk5LSkVDbEd3RHg2ejNySGMvOFZqelJFbkMzYUhiSFhTNzgyY2EvemlmbTVTWXFyU2JMU2Q3V3E1bHM5dlF4NTAKM01JVGxTRlhMa2lua1dhRjN5WFhXZEVMWG03ZVR3WitOcUFuRGVGcVovNkUwczV5N3FFVUt2RkNOc0N5aW1lMgpqcFR3YitXTzdMM0lrSFpTYVR0K3ZFZTA5RFpPbk9Xa2ZnVXhHVnlITEdsNFBJckNmeWtQNGdWcGlDK1NrRkZECjVRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-3
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 4
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeG54eGhJdkZYbE41Sm42byt3cFQKV2lLd3M4bjZFRzJaNStFVjRLWTRsbXpoU2txeTBMU1hHYjRKa0dRM21CUnpmQnptUk8zNXN1NWM5MmFqenVOQwpSTm8rUGhrYmoyRzR1SmRySG44Tm0wTVI3N1MyKy9iaTlzWWVZMVh2L2tJMHhSbFlMOXFkVUczWjVVejBXWmM0CjgxQWNIbVREK25DZkZrSENmQkxUODEvZXhiL1BzWlZpcmVTTkVOaUlEMGxkcHFhaUpYOURCZk5XUmpuc1granIKaW5KL0lqRHVIUXloNWVKL0NTRGptbnRZS2FvMzBOV1hGT05DSWlqb1diWDZZWU9uMys3b2FWMDkybmpuakV3dAoyZGtKdzV2L2tWOEIxUlhiRGdmSVdtc0lNUmY4UTh4U3hBRng0R0lwc0IvcTNKVDdFVzRSMlo5amJhMi9BSXl2Ckp3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-4
- Log: ''
  Name: ValidatorRegistration
  Data:
    OperatorIds:
    - 1
    - 2
    - 3
    - 4
    PublicKey: '0xb79d0e7e5004f1679bd96e89fd94c5cc2ee5c368d9207b4c778b6983f288e5f4cee3bf84c7ff4a16935140da31615b9f'
    SharesPublicKeys:
    - '0xb86da27142cc6ffa7b74dd377d74dcc0c08d9e4b3ea7514b97b55b5d3349317e5ce93b4a59494350d62950393843a2f1'
    - '0x92708af047d3e01638504723742a41f6cafee5ce6d7593f4df3af217e7fc83ef43c412088d3c43d6e87692e08bef0b98'
    - '0xa6002d6198e0cc9ca9a4476bc161f0dd2310722bcbb7252a368752820e1a77376e812cf0267e8c02188ffec75aa2f803'
    - '0xb607d11153541bb14e77b986200177537a7d425ffdcb89ff1d7eb3aca3e71cfadddd187e3df821a6b3ea546485a479a0'
    EncryptedKeys:
    - c/QVqmDG6Cr2nGuAE3uayml5iqd5N0urpPJxbDIW1AGF7FE+FVjspSMmWVtzvWkQVYmtt3rXgyG/OLmMNAV55KCWtV0ZiQvc6sDQp8Qvdz0uVyYchTHDt31OTEekJ9v1j7JN1BawvxFH7ZWxIqEjOhkMPyvXP3v2d24GTlnSkWzemXcIW5SB7wcaJLrWj1KSsbWJvv6hz5bikxwhy9n4VK97vXtWOlYeoOVvWQf0vXAQElNhUxSJSGYdA9j55kE5i1Ba+nz5Ch8H/kCe4To8O6ApXJvMZO9E6OHUZMxdJkKec7Hj6eHxgEEC7tRJq1CKLTRXQZO6A/a1nDJDXldlYA==
    - Aenfk+awblZfrLiBUEfQApQJvRNNkCbkqrew5DmTWui5wXHVfFm4S9AdSFxYkQffpg/XEAw7RpBBdgRDOMCffQ0X8cwn1YyoGnQZBwIRIjRHuUEmqs7K3wG0UiwEl8fC7bMIGWTo4+pX744uRzyCzpCu4lVAdl6gI0oeRsUdjS+xxXTUzSzcXcR/YgHTv/Q6QF67+tqEzk2wI4N1q1lQ1xmBU7B2OEOChcSZBm9ZO8/fxGNPD2mvW8VCIM8/HLC7WoIVUCi/MQwEeem6K9Yxz8foL6SX9/V/G0u9YcUj6FioIJNw5593ktsqZBEcnzn82Zcds0CfNua+9rSdNy72eg==
    - vZJboRjh4/QYJVgq/XaSPhWQWFbDLStKRAsIcFplU2F6kBAs+pXJ4jXMLMvK61nH4E64QeRSYBV6GOwUDBj2Pv3FaW1WAlPLlwFHpTeaTAKtrPOW7Anu+hLJnHgDwtSgP2V0w/5cx49bkMI+UhSVVINyGD/ccycS0cjxCz+/1KMECN6cmdBrMuSdRYB9uJYnNI4bkfOEBBj2riG9qP+hvJmlunfqphLORCJJUQj4x1tR4dIygMdnN5JhK00y5OBEPwm3VRrcvlmYUdKpHf4Jbe4kFEtorRC10dYLER1TQ9JGNNPSFJcGxU1Xh8LCqsT22M1ZEIw9Ejs1JDcUbHWkNQ==
    - CeHGeW3QQDowYn+5ShFsLaIXqWidgUAaKICBRpBY/r7AwlXFoYfgorseiPmZMeNorIIxZ0NlGcLAY8W8QYofKz7FdgnD82OgpftQ57b1dVE3LewCqKvIo3mkzM2iSWM1hKnDO0F8z3aGClNWmCTEbpGQ3q4Os6emxluRJPZUVb0PSbO3jOyGIAPg1f5Wy5uA2dghdZ/iBGn8ewxsos5gge+8OBWseSNqgAgp2FUi+2ISSYlaNrFLOsSa6D2Igw3hORSJMnVKZIV06JAe51Hnk6fIRK3TcDvyWdmK9c/g/6W5fUvX9TQ1Smwyx7LixW47Y+fR5r0sWqwBAnby0rGiBw==
