- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 1
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBejdyOGJUWXNtQXRwbGp6a25YMTEKci9EdDBhc2E5ZXFnOC9PeGZmcExHTGZBYkduNFV6SStuUlF0dER0alIvZWhQWC9KVndiSEFpTnQ1MHJucXMweApxeDE5cGJ2bXhyakNQS0NaTXR2RzBFeGZORlFtWHdaZGZmQzg5WElwOHBHZG9yanRqWFlmWVF3ZS9WZGRRMC9HCk5LSkVDbEd3RHg2ejNySGMvOFZqelJFbkMzYUhiSFhTNzgyY2EvemlmbTVTWXFyU2JMU2Q3V3E1bHM5dlF4NTAKM01JVGxTRlhMa2lua1dhRjN5WFhXZEVMWG03ZVR3WitOcUFuRGVGcVovNkUwczV5N3FFVUt2RkNOc0N5aW1lMgpqcFR3YitXTzdMM0lrSFpTYVR0K3ZFZTA5RFpPbk9Xa2ZnVXhHVnlITEdsNFBJckNmeWtQNGdWcGlDK1NrRkZECjVRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-1
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 2
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNWFLQzRob1pzaVVPbDAyNGNqNUMKZWdHUUhMRERqelZ3eTFEWHFvcTRlL0daWmdDQ3dpek81TVcwTjZUejJjNUtDNlZDNnF3d3hsWHJwaUh1bG9HcgpPSWZEODlTTks1RGh4bWpzcUpieHZUVHlaOFNGUUthb2lNRXd6WXVvUldacU04VnM3S2RvMUhMQU1RN2p4dXFwCmp0SUxIaU9EeHBUeU9nUmhPSnJhKzRUQzd6aTBWOUR4MnN0U1RVZlV2M1c3c0UwNWgwcUNzYVhmMERwd3hqVjgKbUJ6L2UwWjZiNFpEa3JIYkJRSk1ZTnJzcncrM210RjJxV3NhS1JzNWk1Ui9lMUZCMVJBaHNYMENBTHZpSTEyagpSMUNiaWVIQnh3RVZ2V1EzYm1qQVdXSW40SENVdmdacC9Ncm5OekxldUxaVUhKa1EzUXB5Q0IxQXlaSHRES1hzCmx3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-2
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 3
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdTVTeXhYR0VNc1RYd0NJeUw3WE0KOW5rcTcyU3orZTBJQVZPRmtvckNnQjhXVTg5ellMa3dDZEw0SktRM3JQRlhLZ3BScTJCOWlJYnpXUXUzVkNGagpjUmRxRGYrMUt5ZjY2bHFIKzR3b2Y1dXMwZFpvU1FRRTRxZ2swTHY3WUZkQTdDV0hqbWtkQzNJV3haTkI3dCtBCm1hVEVDbGswcklZY244S0VaN0RMelMwb3ZCNytoK1lKYWV4Z2t2OStjdmE4WWZMeUhyZzNqZytGUDhhWlVsMTcKT21uUVJqL0dHK1pSVkdMcE1mbHdLOFprS3MrNXJONzBUSXB5L3JhRmlRSzF3RmVwTkRReFhVS21QVStBMDZSdQordktpL3hkUEtCb3ljN1N6aTBEQWxCdFhqa2FGdkxQSVJGa2J4a0k1SUtoNnpQbVVYWDlXNEM3SUNJRFB2L1dPCkd3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-3
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 4
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeG54eGhJdkZYbE41Sm42byt3cFQKV2lLd3M4bjZFRzJaNStFVjRLWTRsbXpoU2txeTBMU1hHYjRKa0dRM21CUnpmQnptUk8zNXN1NWM5MmFqenVOQwpSTm8rUGhrYmoyRzR1SmRySG44Tm0wTVI3N1MyKy9iaTlzWWVZMVh2L2tJMHhSbFlMOXFkVUczWjVVejBXWmM0CjgxQWNIbVREK25DZkZrSENmQkxUODEvZXhiL1BzWlZpcmVTTkVOaUlEMGxkcHFhaUpYOURCZk5XUmpuc1granIKaW5KL0lqRHVIUXloNWVKL0NTRGptbnRZS2FvMzBOV1hGT05DSWlqb1diWDZZWU9uMys3b2FWMDkybmpuakV3dAoyZGtKdzV2L2tWOEIxUlhiRGdmSVdtc0lNUmY4UTh4U3hBRng0R0lwc0IvcTNKVDdFVzRSMlo5amJhMi9BSXl2Ckp3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-4
- Log: ''
  Name: ValidatorRegistration
  Data:
    OperatorIds:
    - 1
    - 2
    - 3
    - 4
    PublicKey: '0xb79d0e7e5004f1679bd96e89fd94c5cc2ee5c368d9207b4c778b6983f288e5f4cee3bf84c7ff4a16935140da31615b9f'
    SharesPublicKeys:
    - '0xb19389b279f5b9a549ec2322f7618db01a2296f6fc45b66ec171727b8dc2d87d3e191a81f9f73a07cbbf75684b0ea700'
    - '0xaa229746d5128e162a1e22282ffb9b4424371045104facd4440a3cf9656820c7e018f6f0557d0bcdfc1776d0978fa2fe'
    - '0x89dc4d1e75c790199b31d1eab7cac7521b4e00789d35fa8f4c2f256d26542215a80937bc1166ed56cc51cd3bc260229e'
    - '0x8aece2b348c77316fb775199cb50023f11ced75eb1c01aab9e6c5ad42f5267ce28f0668bc1af2d76a408b125a03b9d4a'
    EncryptedKeys:
    - QQt854JuejNQvg9StZ0YY2SxAg2DBMVIyZFxSpy4ychvoQVeHBdw1bt6PPyX4+rtOX9T3vBQIcRb9y0pDekkjxTaEej03Mr86rqbTUJtS32a+w7RBCEpM5qQ4eRMYaJBoC6J/vXXZ4bgLoGcP0Lc/T6NzcuQos9VXwqZ4iBsJSfbfmINDzUecl9pRrDcuw0D3a3LDjaqnlnZPM7ovHuLzmj3OnhVUNaOhXkaxfvGfGLrHrSOfuAJ97Uz3cpvJa3c+7VcdNxy1AwLsmFdv/xnYXYD3yR+i/+mh50lzvLm+pBa01DtqI4m8Q3q5zyeqD74Hvp738kdab++ATPppwaOKQ==
    - 42aArmvlPrUxRoHE8SIrfDeMHJOZy/XyZUoFXFbjHvKjCH5QFFLKCE97Tv26x0n6qw09Kc44n8oRfdKKNN+x2fxwlAtT3eBlmmoHVARwFxgQQmf2aP2oQXarPG1cWYKWOUxP1V9E5hyrEymhnuyj72jaoSDu0poYkrk12/DUHiqO/9Sp61+pImWkPoili5ZL+KIw5N703wlHbMyYXV2WJPjxdQrSVT3VtYFmDHGz9TIYZij6ieWhYqP7xvhrRWt/HXwE/hdHAZOVx7pBQqCzjSnUpeMQm2n94O3QaHqugMp8nnpWQBRrTVpI6UTrl8iYrFYaUoY8LW0WeGnSVnONRg==
    - C2Pg72ku9fSQyoiyMjl5zelJC4qXWm3oFhtVkbNHzO8WoCJjhHHZtu5EmPXAH6uWs2RXd0ltFz1o7buZe8xW/PZxfXuTBPOh8VbGcDwh6reN2+ewKMFJlEZP+NELOBzehQ/dh1WNenYshrlt/i1mzB06y3cuTd01pUSfSdnSpIJvqt2y019SNCOdvKhaR1TlfLngtU8y6lbfLJfwkjmuvIQhw0tUujii4qurrxOMfYVhj4FEOzT4VMZlHUDKTZqD7nTpwkCO5/ltKIBdYaHTPL0ETf++EphI7GIQuPvk+ycuef81r/HYSiW9Unt8v4hYDSR7KPw91+Ln5VHOUo4lOQ==
    - KqAUUkvFwSs5/llcxUIWMh+D+54veqrrJzV3nJbx7m03OtqJCRvNlD6NjpDAe6jbe0mXgjrjvWFxzVevqsdxfrGHtdmbMAPVi3CXT9UFmtb3JuPkqOplOHp+a8YAaTyhMq+3xmrR71QelBy78faGOxM+o1LVOAJrVi83GjjgLzJp3xMrRMiFjTCWx1fTqoEbHepO3Mydy5YBJidDytD4RCiy9MekddUN00GxdJ4ofLk58WjYZt9rWa56gKmr9Pn+m4tNBRqy9exaXoHPx0N/loGLh4ORQ+UlfiXk65HrO+Af9GrTehRCsTVemJHej/bIns8XIehPMVemqImJdPtPsw==
