- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 1
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdTVTeXhYR0VNc1RYd0NJeUw3WE0KOW5rcTcyU3orZTBJQVZPRmtvckNnQjhXVTg5ellMa3dDZEw0SktRM3JQRlhLZ3BScTJCOWlJYnpXUXUzVkNGagpjUmRxRGYrMUt5ZjY2bHFIKzR3b2Y1dXMwZFpvU1FRRTRxZ2swTHY3WUZkQTdDV0hqbWtkQzNJV3haTkI3dCtBCm1hVEVDbGswcklZY244S0VaN0RMelMwb3ZCNytoK1lKYWV4Z2t2OStjdmE4WWZMeUhyZzNqZytGUDhhWlVsMTcKT21uUVJqL0dHK1pSVkdMcE1mbHdLOFprS3MrNXJONzBUSXB5L3JhRmlRSzF3RmVwTkRReFhVS21QVStBMDZSdQordktpL3hkUEtCb3ljN1N6aTBEQWxCdFhqa2FGdkxQSVJGa2J4a0k1SUtoNnpQbVVYWDlXNEM3SUNJRFB2L1dPCkd3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-1
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 2
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNWFLQzRob1pzaVVPbDAyNGNqNUMKZWdHUUhMRERqelZ3eTFEWHFvcTRlL0daWmdDQ3dpek81TVcwTjZUejJjNUtDNlZDNnF3d3hsWHJwaUh1bG9HcgpPSWZEODlTTks1RGh4bWpzcUpieHZUVHlaOFNGUUthb2lNRXd6WXVvUldacU04VnM3S2RvMUhMQU1RN2p4dXFwCmp0SUxIaU9EeHBUeU9nUmhPSnJhKzRUQzd6aTBWOUR4MnN0U1RVZlV2M1c3c0UwNWgwcUNzYVhmMERwd3hqVjgKbUJ6L2UwWjZiNFpEa3JIYkJRSk1ZTnJzcncrM210RjJxV3NhS1JzNWk1Ui9lMUZCMVJBaHNYMENBTHZpSTEyagpSMUNiaWVIQnh3RVZ2V1EzYm1qQVdXSW40SENVdmdacC9Ncm5OekxldUxaVUhKa1EzUXB5Q0IxQXlaSHRES1hzCmx3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-2
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 3
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeG54eGhJdkZYbE41Sm42byt3cFQKV2lLd3M4bjZFRzJaNStFVjRLWTRsbXpoU2txeTBMU1hHYjRKa0dRM21CUnpmQnptUk8zNXN1NWM5MmFqenVOQwpSTm8rUGhrYmoyRzR1SmRySG44Tm0wTVI3N1MyKy9iaTlzWWVZMVh2L2tJMHhSbFlMOXFkVUczWjVVejBXWmM0CjgxQWNIbVREK25DZkZrSENmQkxUODEvZXhiL1BzWlZpcmVTTkVOaUlEMGxkcHFhaUpYOURCZk5XUmpuc1granIKaW5KL0lqRHVIUXloNWVKL0NTRGptbnRZS2FvMzBOV1hGT05DSWlqb1diWDZZWU9uMys3b2FWMDkybmpuakV3dAoyZGtKdzV2L2tWOEIxUlhiRGdmSVdtc0lNUmY4UTh4U3hBRng0R0lwc0IvcTNKVDdFVzRSMlo5amJhMi9BSXl2Ckp3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-3
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 4
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBejdyOGJUWXNtQXRwbGp6a25YMTEKci9EdDBhc2E5ZXFnOC9PeGZmcExHTGZBYkduNFV6SStuUlF0dER0alIvZWhQWC9KVndiSEFpTnQ1MHJucXMweApxeDE5cGJ2bXhyakNQS0NaTXR2RzBFeGZORlFtWHdaZGZmQzg5WElwOHBHZG9yanRqWFlmWVF3ZS9WZGRRMC9HCk5LSkVDbEd3RHg2ejNySGMvOFZqelJFbkMzYUhiSFhTNzgyY2EvemlmbTVTWXFyU2JMU2Q3V3E1bHM5dlF4NTAKM01JVGxTRlhMa2lua1dhRjN5WFhXZEVMWG03ZVR3WitOcUFuRGVGcVovNkUwczV5N3FFVUt2RkNOc0N5aW1lMgpqcFR3YitXTzdMM0lrSFpTYVR0K3ZFZTA5RFpPbk9Xa2ZnVXhHVnlITEdsNFBJckNmeWtQNGdWcGlDK1NrRkZECjVRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-4
- Log: ''
  Name: ValidatorRegistration
  Data:
    OperatorIds:
    - 1
    - 2
    - 3
    - 4
    PublicKey: '0xb79d0e7e5004f1679bd96e89fd94c5cc2ee5c368d9207b4c778b6983f288e5f4cee3bf84c7ff4a16935140da31615b9f'
    SharesPublicKeys:
    - '0x85f3350bea80136e617bba8086e9c949d5d5eb6125001ea959457f20e14c5dd2f40c6c4d70368bd16a991df13c212920'
    - '0x8b4ff86d08da07b67166f16a0535d1d91fc9de2cd653206b55e5a7b216c0f925a947e519686107aa7461a04adf6c946c'
    - '0x8d8cfb847cb03ec630db7f9e4c2bd3e5184a3b57972fcb0ee6e7470e0c2759f2b825b4cbdc6adfe5015ee26f0faa3529'
    - '0xb6b12728eb31ee7e4fabfa60677d28df3458fd77443781762e1b68718b12084aafefef6f272b12360dd8338e3ab53be2'
    EncryptedKeys:
    - i1y2NDHCfD255xDQ9lqDtlk+zQ63oJRq3wFj31usEHAu2Gq6WCN1qHMXqaAelQVlSPFKpCM+CcFfxS0QLMub/nuLlsZdig/5C+ut4lukVwS1S/hmEV6fp9x1BhNOG0fmE9CurCmKNB6RUVIPAFwMpPICTSyJRbJbfn0SdYzH5i2ZLoHyJ4Vtgx0/bkQk9dzsMi9zP4StR2q9bl3/b6IqWnj+arBAxu+yqaP1fVK1y1F6J11/+Q4BXL7Ht20vxjmwbeIPxn1N29jq+gbB4uFz4jpK0qlCr0EP2QU8O9XcaBEYfFdG5d7NuBsb+8zZI/qSAXpoA6tg9tWW6WdDf373vA==
    - WP0Qfws+wCqLYRRL1O2XH7gnhuh445c5EKgxYw8HBsq0Q9zMhoFSGfpH4zbPHRpVq83gPSUyFvIH8iYSwPVKuZN3UFzRokHeryhV7R0qaZ3VXmZoWZGLX84eD/1cTGhPyz5HSN0/GiB5CskS+HmdK+gKxsd099oJriEeVcLUyiVXzMYkRXwUWkYSanPHOokOjzeWmla8izjMZWqUci0zZthFO4dzXCQWye+3s9oVAZERf/gDH46vnWsILTjO1c8rP0m4D033JRbsH7bufPlPEU38ZEqFkJQ5mi4OEm+kpnk5pc11T1bUCXyt71Fw9V0QfqPm4ck0x5rp9e/NnjXOMQ==
    - Pm7TWnCq7NrVYXWzE3Efc3BLmSF3tJXO/1FhM/nRIYQPvWfEBZMy18yeK+bhslYwRu4XjsasX6sjJ3JG+jaDXu4Lc5GzMhUNwvFUofrc7hlyFBlMEn079tqxPxWaR7I+S6MvJ4nJWPIs5RgHAqgHxZj6nE3bn6uAWaI/AEKL0b3ESM3hDMxxpehIORQVsuh2CS1LGSsQghIW4mfSBOdWEysJTgRvX8XQNVnLo2ZLGAExLCMZg/C6AZqvtsuUPvK5uW+OJwOgoyW7ZR2kvcAINJjh5Bmkba1qohwtxpekQLXLqwCFJXtW73pFFQRzOD7Y/IItrwQMsrxsg/vMs5MwuQ==
    - v/MwQxGdrpt0KmWshn4apNlGSEETxx4o0mes6MNBZB3g43QKQ8SGpbczjyZ9dcSWcMwRFLrD/YF4xKBrtX4/aqyMyn91wzK5uYup6xPv29jS+s06GjjASjzNfVmAWOecqhyt77Pqo+R7zsnBtRZ9cY4Az3zL0YOcsjCqbT5ZxWfYyIu3NBse+vkr5tfetvK7rioek8lwa7pPgJmV/bgZPgAhpaSAww5GYt+djjdv+MuWOTAJ6af+vHXGVRrZMj//w8xp7Zh1vFyjjo5A9P7zowVbIss9BdG0CTe13Lv+s/3DvzPoRAR49wzoodfFa30XP36xpb1xxx6QZ3Yu2jIFNA==
