- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 1
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeG54eGhJdkZYbE41Sm42byt3cFQKV2lLd3M4bjZFRzJaNStFVjRLWTRsbXpoU2txeTBMU1hHYjRKa0dRM21CUnpmQnptUk8zNXN1NWM5MmFqenVOQwpSTm8rUGhrYmoyRzR1SmRySG44Tm0wTVI3N1MyKy9iaTlzWWVZMVh2L2tJMHhSbFlMOXFkVUczWjVVejBXWmM0CjgxQWNIbVREK25DZkZrSENmQkxUODEvZXhiL1BzWlZpcmVTTkVOaUlEMGxkcHFhaUpYOURCZk5XUmpuc1granIKaW5KL0lqRHVIUXloNWVKL0NTRGptbnRZS2FvMzBOV1hGT05DSWlqb1diWDZZWU9uMys3b2FWMDkybmpuakV3dAoyZGtKdzV2L2tWOEIxUlhiRGdmSVdtc0lNUmY4UTh4U3hBRng0R0lwc0IvcTNKVDdFVzRSMlo5amJhMi9BSXl2Ckp3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-1
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 2
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBejdyOGJUWXNtQXRwbGp6a25YMTEKci9EdDBhc2E5ZXFnOC9PeGZmcExHTGZBYkduNFV6SStuUlF0dER0alIvZWhQWC9KVndiSEFpTnQ1MHJucXMweApxeDE5cGJ2bXhyakNQS0NaTXR2RzBFeGZORlFtWHdaZGZmQzg5WElwOHBHZG9yanRqWFlmWVF3ZS9WZGRRMC9HCk5LSkVDbEd3RHg2ejNySGMvOFZqelJFbkMzYUhiSFhTNzgyY2EvemlmbTVTWXFyU2JMU2Q3V3E1bHM5dlF4NTAKM01JVGxTRlhMa2lua1dhRjN5WFhXZEVMWG03ZVR3WitOcUFuRGVGcVovNkUwczV5N3FFVUt2RkNOc0N5aW1lMgpqcFR3YitXTzdMM0lrSFpTYVR0K3ZFZTA5RFpPbk9Xa2ZnVXhHVnlITEdsNFBJckNmeWtQNGdWcGlDK1NrRkZECjVRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-2
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 3
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNWFLQzRob1pzaVVPbDAyNGNqNUMKZWdHUUhMRERqelZ3eTFEWHFvcTRlL0daWmdDQ3dpek81TVcwTjZUejJjNUtDNlZDNnF3d3hsWHJwaUh1bG9HcgpPSWZEODlTTks1RGh4bWpzcUpieHZUVHlaOFNGUUthb2lNRXd6WXVvUldacU04VnM3S2RvMUhMQU1RN2p4dXFwCmp0SUxIaU9EeHBUeU9nUmhPSnJhKzRUQzd6aTBWOUR4MnN0U1RVZlV2M1c3c0UwNWgwcUNzYVhmMERwd3hqVjgKbUJ6L2UwWjZiNFpEa3JIYkJRSk1ZTnJzcncrM210RjJxV3NhS1JzNWk1Ui9lMUZCMVJBaHNYMENBTHZpSTEyagpSMUNiaWVIQnh3RVZ2V1EzYm1qQVdXSW40SENVdmdacC9Ncm5OekxldUxaVUhKa1EzUXB5Q0IxQXlaSHRES1hzCmx3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-3
- Log: ''
  Name: OperatorRegistration
  Data:
    Id: 4
    PublicKey: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdTVTeXhYR0VNc1RYd0NJeUw3WE0KOW5rcTcyU3orZTBJQVZPRmtvckNnQjhXVTg5ellMa3dDZEw0SktRM3JQRlhLZ3BScTJCOWlJYnpXUXUzVkNGagpjUmRxRGYrMUt5ZjY2bHFIKzR3b2Y1dXMwZFpvU1FRRTRxZ2swTHY3WUZkQTdDV0hqbWtkQzNJV3haTkI3dCtBCm1hVEVDbGswcklZY244S0VaN0RMelMwb3ZCNytoK1lKYWV4Z2t2OStjdmE4WWZMeUhyZzNqZytGUDhhWlVsMTcKT21uUVJqL0dHK1pSVkdMcE1mbHdLOFprS3MrNXJONzBUSXB5L3JhRmlRSzF3RmVwTkRReFhVS21QVStBMDZSdQordktpL3hkUEtCb3ljN1N6aTBEQWxCdFhqa2FGdkxQSVJGa2J4a0k1SUtoNnpQbVVYWDlXNEM3SUNJRFB2L1dPCkd3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K
    Name: Operator-4
- Log: ''
  Name: ValidatorRegistration
  Data:
    OperatorIds:
    - 1
    - 2
    - 3
    - 4
    PublicKey: '0xb79d0e7e5004f1679bd96e89fd94c5cc2ee5c368d9207b4c778b6983f288e5f4cee3bf84c7ff4a16935140da31615b9f'
    SharesPublicKeys:
    - '0xa418e2725500321e99b3edc9a2f5730d326744066b1f3aab82c64d6275cdabd99ba61225983a7bf93ff1809732d4ead9'
    - '0xab63eebf074bd9b0047dd0b58dcd396f2bd9cdcbdd4166e088023f6891c9f750926dfdac4d131d374b89063b8a522988'
    - '0xb4f4064c827e9ea41d2106afb707c076073e15c3191c2de151912dd367d382199c40dcd2ad1110e78de459452446528a'
    - '0xaaecac133257d733d30c8cfd9680f37930e8a3bf1d780242a765532d32704a626b1b73211b53dc284009be4e9da95cee'
    EncryptedKeys:
    - cX6AAgA/09MucPdpYo9MpK+uGmdBVdgbj2rapmvbe4qny9U+IWrwsAvCTqpOW+EJqAXU9c/KyXmjEmilA/SBQaCEhu89yRPz7a8udaX528ed3JK5TcgU1jAs4v5sOMhL/Bkog3H5BK51sC83jGb8BWW7/fDymLkuoJRvlN8rWaG17l0j0dP8l9fG5DVCnnKmc7x/c1dvpnVobmU5PIT0dTmJtWbsaoBzCCYvFWocIroLqSPD2hq5SLi7Pi5OZ26okgLO4Kuy7gCbL3q1lFyWZfJurD0ARFeVBgnuaxdRrLO7gxZKLbeFrOwMeTT9yqCvDzjil224Ys0crLgTPU20aQ==
    - bZ+pUS2zs01wdNk7giqDLcr+hHyCixSMBhtTT3HmWupYenFlmKSMOXoYzPfj+J+/sfka63QonhZRIdiBvpWpqppFXWAyC0r8N+8wezTAmKVhNLUfkK/mbrEJ1w5LudY+8tYaLpUI0MIy29CPE4E7/Q+beJBm4h2kFQb9OjC4jNdFUTjiMi/9hAMIOVimIvf637nkQKi523aNeRzIz/LY0bblINesokZ7Rl216fXzvJ+u7FNT9k7GxJvBkSGWQJ0enEU5JlzJ6bCRIOMyD+XGXDKN4akZCHAsOSAYdPDCWY8GictR3jKI5WUziXQAylUztTEC3k9lm1vq8Ma5yu193w==
    - P2uT1tEU3DnxNGjzNeqZMfl49DVj5UDK93+nAnsjkxvSvWhunoBNAUrcLrgf6IgX2umpGr98PwMDMtBkBmN88WY5jw302oiw6Sd4AFHhZOvU0waZru6llIVSIFuplrGaUhTgpgU7DkYDvG58gM5WuiPxwil8E9QGHmgb7ROwuMuJJBMD//04KYgxWXE5vqXDn+Kb0DvvNgbNVu50DxZL2RmLIKio+fiBDcWGtnUvJylF6moIxHaU2GvPmhIKKBlyBhXTJhwiNlKw6/ykcDm1Sau5jc6uhjvi9fUfstfEX04rhebojh4uDJI5WzT2CtcxEtfwE0Ukc6pwhaLG/nKubg==
    - fTcORoa0k1VtQqjJ33De31daYM8EZp9wcDCoraUhUNGfa4ZQL5k7+GCWwvcmV4PXFwr7VA0LF8DW2AF1H5PI8Dxarpt83FmSVEMjQf9iou3yKllfrDnbKvuTUkTWCHcWGSL3VwXW6PryHzfLozydHmh4QHjgL+3fYJ3OMmxi+Jf9QL9XrPqqb4hej3Z3Wt9xzjukgGJwsACx2eP9YzXma8Hn9dqisEDEfyUDseQT+tmDRKOQEZokrJs3u/tTZWk2st5F1kvR+QYoEP3YfJtjkReeO2WCnmSks5TQEkU4OXJn31LJlE6/VNTn4NhycHS2/aQLqoPOBFrdUCY6TqWVPg==
